
PARAMETER_TYPE_INT = 0
PARAMETER_TYPE_FLOAT = 1
PARAMETER_TYPE_BOOLEAN = 2
PARAMETER_TYPE_STRING = 3
PARAMETER_TYPE_USER_DATASET = 4
PARAMETER_TYPE_DATE = 5
PARAMETER_TYPE_USER_DATASET_ROW = 6

ARGS_FILE_NAME = "args.json"

RESULTS_FILE_NAME = "results.json"

MESSAGE_LEVEL_INFO = 0
MESSAGE_LEVEL_WARNING = 1
MESSAGE_LEVEL_ERROR = 2

from .TexNetWebToolLaunchHelper import TexNetWebToolLaunchHelper